/*
 * 2.cpp
 *
 *  Created on: Jul 7, 2016
 *      Author: tpl
 */
#include "solutions.h"
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

int problem2() {
	//generate fibonacci numbers
	int i = 1; // 1
	int j = 2; // 2
	int k = i + j; // 3
	int l = j + k; // 5
	int m = k + l; // 8

	int sum = 2;

	while (m < 4000000) {
		sum = sum + m;

		// generate next set
		i = l; // 5
		j = m; // 8
		k = i + j; // 13
		l = j + k; // 21
		m = k + l; // 34
	}
	return sum;
}


